import { Job } from './types';

export const dummyJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "Google",
    company_logo: "https://img.logo.dev/google.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Bangalore, India",
    job_type: "Full-Time",
    work_mode: "Remote",
    salary: "₹25,00,000 - ₹35,00,000",
    industry_type: "IT Services",
    posted_date: "2024-07-20",
    description: "Lead the development of our next-generation web platform. Must be proficient in React, Next.js, and have a keen eye for UI/UX.",
    experience_level: "Senior-Level"
  },
  {
    id: "2",
    title: "Backend Engineer (Python/Django)",
    company: "Microsoft",
    company_logo: "https://img.logo.dev/microsoft.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Mumbai, India",
    job_type: "Full-Time",
    work_mode: "Onsite",
    salary: "₹15,00,000 - ₹22,00,000",
    industry_type: "FinTech",
    posted_date: "2024-07-18",
    description: "Design and build scalable APIs and microservices using Python and Django. Experience with AWS and PostgreSQL is a plus.",
    experience_level: "Mid Level"
  },
  {
    id: "3",
    title: "Associate UI/UX Designer",
    company: "Adobe",
    company_logo: "https://img.logo.dev/adobe.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Remote",
    job_type: "Contract",
    work_mode: "Remote",
    salary: "₹8,00,000 - ₹12,00,000",
    industry_type: "Design",
    posted_date: "2024-07-15",
    description: "Create beautiful, user-centric designs for our web and mobile applications. Work closely with product and engineering teams.",
    experience_level: "Entry-Level"
  },
  {
    id: "4",
    title: "Lead Data Scientist",
    company: "Amazon",
    company_logo: "https://img.logo.dev/amazon.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Hyderabad, India",
    job_type: "Full-Time",
    work_mode: "Hybrid",
    salary: "₹30,00,000 - ₹45,00,000",
    industry_type: "AI/ML",
    posted_date: "2024-07-12",
    description: "Lead a team of data scientists to analyze large datasets, build predictive models, and deliver actionable insights for business growth.",
    experience_level: "Executive Level"
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "IBM",
    company_logo: "https://img.logo.dev/ibm.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Chennai, India",
    job_type: "Full-Time",
    work_mode: "Onsite",
    salary: "₹14,00,000 - ₹20,00,000",
    industry_type: "Cloud Computing",
    posted_date: "2024-07-11",
    description: "Automate CI/CD pipelines, manage cloud infrastructure on GCP/Azure, and ensure high availability and system reliability.",
    experience_level: "Mid Level"
  },
  {
    id: "6",
    title: "Product Manager",
    company: "Meta",
    company_logo: "https://img.logo.dev/meta.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Delhi, India",
    job_type: "Full-Time",
    work_mode: "Hybrid",
    salary: "₹20,00,000 - ₹30,00,000",
    industry_type: "Software",
    posted_date: "2024-07-10",
    description: "Define product vision, strategy, and roadmap. Work with cross-functional teams to deliver exceptional products.",
    experience_level: "Senior-Level"
  },
  {
    id: "7",
    title: "Junior QA Engineer",
    company: "Salesforce",
    company_logo: "https://img.logo.dev/salesforce.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Pune, India",
    job_type: "Part-Time",
    work_mode: "Remote",
    salary: "₹6,00,000 - ₹10,00,000",
    industry_type: "Quality Assurance",
    posted_date: "2024-07-08",
    description: "Develop and execute manual and automated test plans, identify bugs, and ensure the overall quality of our products.",
    experience_level: "Entry-Level"
  },
  {
    id: "8",
    title: "Digital Marketing Specialist",
    company: "Netflix",
    company_logo: "https://img.logo.dev/netflix.com?token=pk_GXHi5vUDRwm1xphnJaliqA",
    location: "Remote",
    job_type: "Contract",
    work_mode: "Remote",
    salary: "₹7,00,000 - ₹11,00,000",
    industry_type: "Marketing",
    posted_date: "2024-07-05",
    description: "Plan and execute digital marketing campaigns across various channels, analyze performance metrics, and grow our brand presence online.",
    experience_level: "Mid Level"
  }
]; 